// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type LoginRequestDto = {
    [key: string]: unknown;
};

export type RefreshTokenRequestDto = {
    [key: string]: unknown;
};

export type SearchUserDto = {
    [key: string]: unknown;
};

export type UserInfoDto = {
    [key: string]: unknown;
};

export type ChangeUserInfoDto = {
    [key: string]: unknown;
};

export type SearchCompanyDto = {
    [key: string]: unknown;
};

export type CompanyInfoDto = {
    [key: string]: unknown;
};

export type SearchProgramDto = {
    [key: string]: unknown;
};

export type ProgramDto = {
    level?: number;
    treeKey?: string;
    treePath?: string;
};

export type SearchRoleDto = {
    [key: string]: unknown;
};

export type RoleDto = {
    [key: string]: unknown;
};

export type AuthControllerLoginData = {
    body: LoginRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AuthControllerLoginResponses = {
    200: unknown;
};

export type AuthControllerRefreshTokenData = {
    body: RefreshTokenRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/refresh-token';
};

export type AuthControllerRefreshTokenResponses = {
    200: unknown;
};

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type AuthControllerLogoutResponses = {
    200: unknown;
};

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type AuthControllerMeResponses = {
    200: unknown;
};

export type UsersControllerGetListUserInfoData = {
    body: SearchUserDto;
    path?: never;
    query?: never;
    url: '/api/api/adm/user/getListUserInfo';
};

export type UsersControllerGetListUserInfoResponses = {
    200: unknown;
};

export type UsersControllerGetUserInfoData = {
    body: SearchUserDto;
    path?: never;
    query?: never;
    url: '/api/api/adm/user/getUserInfo';
};

export type UsersControllerGetUserInfoResponses = {
    200: unknown;
};

export type UsersControllerCreateUserData = {
    body: UserInfoDto;
    path?: never;
    query?: never;
    url: '/api/api/adm/user/createUser';
};

export type UsersControllerCreateUserResponses = {
    200: unknown;
};

export type UsersControllerUpdateUserData = {
    body: UserInfoDto;
    path?: never;
    query?: never;
    url: '/api/api/adm/user/updateUser';
};

export type UsersControllerUpdateUserResponses = {
    200: unknown;
};

export type UsersControllerChangeUserInfoData = {
    body: ChangeUserInfoDto;
    path?: never;
    query?: never;
    url: '/api/api/adm/user/changeUserInfo';
};

export type UsersControllerChangeUserInfoResponses = {
    200: unknown;
};

export type UsersControllerResetUserPasswordData = {
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/api/api/adm/user/resetUserPassword';
};

export type UsersControllerResetUserPasswordResponses = {
    200: unknown;
};

export type UsersControllerSaveUserSettingData = {
    body: UserInfoDto;
    path?: never;
    query?: never;
    url: '/api/api/adm/user/saveUserSetting';
};

export type UsersControllerSaveUserSettingResponses = {
    200: unknown;
};

export type CompaniesControllerGetListCompanyInfoData = {
    body: SearchCompanyDto;
    path?: never;
    query?: never;
    url: '/api/adm/company/getListCompanyInfo';
};

export type CompaniesControllerGetListCompanyInfoResponses = {
    200: unknown;
};

export type CompaniesControllerGetCompanyInfoData = {
    body: SearchCompanyDto;
    path?: never;
    query?: never;
    url: '/api/adm/company/getCompanyInfo';
};

export type CompaniesControllerGetCompanyInfoResponses = {
    200: unknown;
};

export type CompaniesControllerCreateCompanyData = {
    body: CompanyInfoDto;
    path?: never;
    query?: never;
    url: '/api/adm/company/createCompany';
};

export type CompaniesControllerCreateCompanyResponses = {
    200: unknown;
};

export type CompaniesControllerUpdateCompanyData = {
    body: CompanyInfoDto;
    path?: never;
    query?: never;
    url: '/api/adm/company/updateCompany';
};

export type CompaniesControllerUpdateCompanyResponses = {
    200: unknown;
};

export type ProgramsControllerGetProgramListData = {
    body: SearchProgramDto;
    path?: never;
    query?: never;
    url: '/api/adm/program/getProgramList';
};

export type ProgramsControllerGetProgramListResponses = {
    200: unknown;
};

export type ProgramsControllerGetProgramData = {
    body: SearchProgramDto;
    path?: never;
    query?: never;
    url: '/api/adm/program/getProgram';
};

export type ProgramsControllerGetProgramResponses = {
    200: unknown;
};

export type ProgramsControllerInsertProgramData = {
    body: ProgramDto;
    path?: never;
    query?: never;
    url: '/api/adm/program/insertProgram';
};

export type ProgramsControllerInsertProgramResponses = {
    200: unknown;
};

export type ProgramsControllerUpdateProgramData = {
    body: ProgramDto;
    path?: never;
    query?: never;
    url: '/api/adm/program/updateProgram';
};

export type ProgramsControllerUpdateProgramResponses = {
    200: unknown;
};

export type ProgramsControllerDeleteProgramsData = {
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/api/adm/program/deletePrograms';
};

export type ProgramsControllerDeleteProgramsResponses = {
    200: unknown;
};

export type ProgramsControllerGetPermissionByProgramData = {
    body: SearchProgramDto;
    path?: never;
    query?: never;
    url: '/api/adm/program/getPermissionByProgram';
};

export type ProgramsControllerGetPermissionByProgramResponses = {
    200: unknown;
};

export type ProgramsControllerSavePermissionsByProgramData = {
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/api/adm/program/savePermissionsByProgram';
};

export type ProgramsControllerSavePermissionsByProgramResponses = {
    200: unknown;
};

export type RolesControllerGetRoleListData = {
    body: SearchRoleDto;
    path?: never;
    query?: never;
    url: '/api/adm/role/getRoleList';
};

export type RolesControllerGetRoleListResponses = {
    200: unknown;
};

export type RolesControllerGetRoleData = {
    body: SearchRoleDto;
    path?: never;
    query?: never;
    url: '/api/adm/role/getRole';
};

export type RolesControllerGetRoleResponses = {
    200: unknown;
};

export type RolesControllerInsertRoleData = {
    body: RoleDto;
    path?: never;
    query?: never;
    url: '/api/adm/role/insertRole';
};

export type RolesControllerInsertRoleResponses = {
    200: unknown;
};

export type RolesControllerUpdateRoleData = {
    body: RoleDto;
    path?: never;
    query?: never;
    url: '/api/adm/role/updateRole';
};

export type RolesControllerUpdateRoleResponses = {
    200: unknown;
};
