// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type LoginRequestDto = {
    username: string;
    password: string;
    tenantId: string;
};

export type LoginResponseDto = {
    accessToken: string;
    accessExpireIn: number;
    refreshToken: string;
    refreshExpireIn: number;
};

export type RefreshTokenRequestDto = {
    refreshToken: string;
};

export type RefreshTokenResponseDto = {
    accessToken: string;
    accessExpireIn: number;
    refreshToken: string;
    refreshExpireIn: number;
};

export type UpdatePreferencesDto = {
    langVal?: string;
    sysModVal?: string;
    dtFmtVal?: string;
    sysColrVal?: string;
    coId?: string;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: string;
    updatedAt?: string;
    useFlg?: boolean;
    procFlag?: string;
};

export type SuccessDto = {
    success: boolean;
    rows?: number;
};

export type PaginationDto = {
    pageSize: number;
    current: number;
};

export type SortDto = {
    sortField?: string;
    sortType?: 'ASC' | 'DESC';
};

export type DynamicFilterDto = {
    field: string;
    operator: 'EQUALS' | 'NOT_EQUALS' | 'GREATER_THAN' | 'GREATER_THAN_OR_EQUAL' | 'LESS_THAN' | 'LESS_THAN_OR_EQUAL' | 'LIKE' | 'IN' | 'BETWEEN';
    value?: string;
    valueTo?: string;
    valueType?: 'STRING' | 'NUMBER' | 'DATE' | 'BOOLEAN';
};

export type SearchUserDto = {
    usrId?: string;
    usrNm?: string;
    searchText?: string;
    pagination?: PaginationDto;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    filters?: Array<DynamicFilterDto>;
    coId?: string;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: string;
    updatedAt?: string;
    useFlg?: boolean;
    procFlag?: string;
};

export type UserInfoDto = {
    usrId?: string;
    usrNm?: string;
    usrPwd?: string;
    usrEml?: string;
    usrPhn?: string;
    usrAddr?: string;
    usrDesc?: string;
    usrFileId?: string;
    roleId?: string;
    roleNm?: string;
    langVal?: string;
    sysModVal?: string;
    dtFmtVal?: string;
    sysColrVal?: string;
    coId?: string;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: string;
    updatedAt?: string;
    useFlg?: boolean;
    procFlag?: string;
};

export type UserInfoListDto = {
    userInfo: Array<UserInfoDto>;
    total: number;
};

export type ChangeUserInfoDto = {
    usrId?: string;
    usrNm?: string;
    usrPwd?: string;
    usrEml?: string;
    usrPhn?: string;
    usrAddr?: string;
    usrDesc?: string;
    usrFileId?: string;
    roleId?: string;
    roleNm?: string;
    langVal?: string;
    sysModVal?: string;
    dtFmtVal?: string;
    sysColrVal?: string;
    coId?: string;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: string;
    updatedAt?: string;
    useFlg?: boolean;
    procFlag?: string;
    oldPassword?: string;
    newPassword?: string;
    confirmNewPassword?: string;
};

export type SearchCompanyDto = {
    coNm?: string;
    taxCd?: string;
    coTpCd?: string;
    coNtn?: string;
    searchText?: string;
    pagination?: PaginationDto;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    filters?: Array<DynamicFilterDto>;
    coId?: string;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: string;
    updatedAt?: string;
    useFlg?: boolean;
    procFlag?: string;
};

export type CompanyInfoDto = {
    coNm?: string;
    coTpCd?: string;
    coFrgnNm?: string;
    taxCd?: string;
    taxOfc?: string;
    coLoclNm?: string;
    coAddrVal1?: string;
    coAddrVal2?: string;
    coAddrVal3?: string;
    emlAddr?: string;
    faxNo?: string;
    phnNo?: string;
    slRep?: string;
    webAddr?: string;
    coDesc?: string;
    coAnvDt?: string;
    coSz?: string;
    coNtn?: string;
    empeSz?: string;
    currCd?: string;
    coIndusZn?: string;
    coProd?: string;
    tmZn?: string;
    bankTpCd?: string;
    bankAcctNo?: string;
    bankNm?: string;
    chtrCapiVal?: string;
    estbDt?: string;
    lgoFileId?: string;
    coId?: string;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: string;
    updatedAt?: string;
    useFlg?: boolean;
    procFlag?: string;
};

export type CompanyInfoListDto = {
    companyInfo: Array<CompanyInfoDto>;
    total: number;
};

export type SearchProgramDto = {
    pgmId?: string;
    pgmCd?: string;
    pgmNm?: string;
    pgmTpCd?: string;
    searchText?: string;
    pagination?: PaginationDto;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    filters?: Array<DynamicFilterDto>;
    coId?: string;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: string;
    updatedAt?: string;
    useFlg?: boolean;
    procFlag?: string;
};

export type PermissionDto = {
    permId?: string;
    permCd?: string;
    permNm?: string;
    pgmId?: string;
    coId?: string;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: string;
    updatedAt?: string;
    useFlg?: boolean;
    procFlag?: string;
};

export type ProgramDto = {
    level?: number;
    treeKey?: string;
    treePath?: string;
    pgmId?: string;
    pgmCd?: string;
    pgmNm?: string;
    pgmTpCd?: 'MENU' | 'UI';
    prntPgmId?: string;
    dspOrder?: number;
    pgmRmk?: string;
    permList?: Array<PermissionDto>;
    coId?: string;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: string;
    updatedAt?: string;
    useFlg?: boolean;
    procFlag?: string;
};

export type ProgramListDto = {
    programList: Array<ProgramDto>;
    total: number;
};

export type SearchRoleDto = {
    roleId?: string;
    roleCd?: string;
    roleNm?: string;
    pgmId?: string;
    permId?: string;
    searchText?: string;
    pagination?: PaginationDto;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    filters?: Array<DynamicFilterDto>;
    coId?: string;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: string;
    updatedAt?: string;
    useFlg?: boolean;
    procFlag?: string;
};

export type RoleAuthDto = {
    roleId?: string;
    pgmId?: string;
    permId?: string;
    pgmCd?: string;
    pgmTpCd?: string;
    permCd?: string;
    activeYn?: boolean;
    coId?: string;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: string;
    updatedAt?: string;
    useFlg?: boolean;
    procFlag?: string;
};

export type RoleDto = {
    roleId?: string;
    roleCd?: string;
    roleNm?: string;
    roleDesc?: string;
    roleAuthList?: Array<RoleAuthDto>;
    coId?: string;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: string;
    updatedAt?: string;
    useFlg?: boolean;
    procFlag?: string;
};

export type RoleListDto = {
    roleList: Array<RoleDto>;
    total: number;
};

export type AuthControllerLoginData = {
    body: LoginRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AuthControllerLoginResponses = {
    200: LoginResponseDto;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerRefreshTokenData = {
    body: RefreshTokenRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/refresh-token';
};

export type AuthControllerRefreshTokenResponses = {
    200: RefreshTokenResponseDto;
};

export type AuthControllerRefreshTokenResponse = AuthControllerRefreshTokenResponses[keyof AuthControllerRefreshTokenResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type AuthControllerLogoutResponses = {
    200: unknown;
};

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type AuthControllerMeResponses = {
    200: unknown;
};

export type AuthControllerUpdatePreferencesData = {
    body: UpdatePreferencesDto;
    path?: never;
    query?: never;
    url: '/api/auth/preferences';
};

export type AuthControllerUpdatePreferencesResponses = {
    200: SuccessDto;
};

export type AuthControllerUpdatePreferencesResponse = AuthControllerUpdatePreferencesResponses[keyof AuthControllerUpdatePreferencesResponses];

export type UsersControllerGetListUserInfoData = {
    body: SearchUserDto;
    path?: never;
    query?: never;
    url: '/api/api/adm/user/getListUserInfo';
};

export type UsersControllerGetListUserInfoResponses = {
    200: UserInfoListDto;
};

export type UsersControllerGetListUserInfoResponse = UsersControllerGetListUserInfoResponses[keyof UsersControllerGetListUserInfoResponses];

export type UsersControllerGetUserInfoData = {
    body: SearchUserDto;
    path?: never;
    query?: never;
    url: '/api/api/adm/user/getUserInfo';
};

export type UsersControllerGetUserInfoResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type UsersControllerGetUserInfoResponse = UsersControllerGetUserInfoResponses[keyof UsersControllerGetUserInfoResponses];

export type UsersControllerCreateUserData = {
    body: UserInfoDto;
    path?: never;
    query?: never;
    url: '/api/api/adm/user/createUser';
};

export type UsersControllerCreateUserResponses = {
    200: SuccessDto;
};

export type UsersControllerCreateUserResponse = UsersControllerCreateUserResponses[keyof UsersControllerCreateUserResponses];

export type UsersControllerUpdateUserData = {
    body: UserInfoDto;
    path?: never;
    query?: never;
    url: '/api/api/adm/user/updateUser';
};

export type UsersControllerUpdateUserResponses = {
    200: SuccessDto;
};

export type UsersControllerUpdateUserResponse = UsersControllerUpdateUserResponses[keyof UsersControllerUpdateUserResponses];

export type UsersControllerChangeUserInfoData = {
    body: ChangeUserInfoDto;
    path?: never;
    query?: never;
    url: '/api/api/adm/user/changeUserInfo';
};

export type UsersControllerChangeUserInfoResponses = {
    200: SuccessDto;
};

export type UsersControllerChangeUserInfoResponse = UsersControllerChangeUserInfoResponses[keyof UsersControllerChangeUserInfoResponses];

export type UsersControllerResetUserPasswordData = {
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/api/api/adm/user/resetUserPassword';
};

export type UsersControllerResetUserPasswordResponses = {
    200: SuccessDto;
};

export type UsersControllerResetUserPasswordResponse = UsersControllerResetUserPasswordResponses[keyof UsersControllerResetUserPasswordResponses];

export type UsersControllerSaveUserSettingData = {
    body: UserInfoDto;
    path?: never;
    query?: never;
    url: '/api/api/adm/user/saveUserSetting';
};

export type UsersControllerSaveUserSettingResponses = {
    200: SuccessDto;
};

export type UsersControllerSaveUserSettingResponse = UsersControllerSaveUserSettingResponses[keyof UsersControllerSaveUserSettingResponses];

export type CompaniesControllerGetListCompanyInfoData = {
    body: SearchCompanyDto;
    path?: never;
    query?: never;
    url: '/api/adm/company/getListCompanyInfo';
};

export type CompaniesControllerGetListCompanyInfoResponses = {
    200: CompanyInfoListDto;
};

export type CompaniesControllerGetListCompanyInfoResponse = CompaniesControllerGetListCompanyInfoResponses[keyof CompaniesControllerGetListCompanyInfoResponses];

export type CompaniesControllerGetCompanyInfoData = {
    body: SearchCompanyDto;
    path?: never;
    query?: never;
    url: '/api/adm/company/getCompanyInfo';
};

export type CompaniesControllerGetCompanyInfoResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type CompaniesControllerGetCompanyInfoResponse = CompaniesControllerGetCompanyInfoResponses[keyof CompaniesControllerGetCompanyInfoResponses];

export type CompaniesControllerCreateCompanyData = {
    body: CompanyInfoDto;
    path?: never;
    query?: never;
    url: '/api/adm/company/createCompany';
};

export type CompaniesControllerCreateCompanyResponses = {
    200: SuccessDto;
};

export type CompaniesControllerCreateCompanyResponse = CompaniesControllerCreateCompanyResponses[keyof CompaniesControllerCreateCompanyResponses];

export type CompaniesControllerUpdateCompanyData = {
    body: CompanyInfoDto;
    path?: never;
    query?: never;
    url: '/api/adm/company/updateCompany';
};

export type CompaniesControllerUpdateCompanyResponses = {
    200: SuccessDto;
};

export type CompaniesControllerUpdateCompanyResponse = CompaniesControllerUpdateCompanyResponses[keyof CompaniesControllerUpdateCompanyResponses];

export type ProgramsControllerGetProgramListData = {
    body: SearchProgramDto;
    path?: never;
    query?: never;
    url: '/api/adm/program/getProgramList';
};

export type ProgramsControllerGetProgramListResponses = {
    200: ProgramListDto;
};

export type ProgramsControllerGetProgramListResponse = ProgramsControllerGetProgramListResponses[keyof ProgramsControllerGetProgramListResponses];

export type ProgramsControllerGetProgramData = {
    body: SearchProgramDto;
    path?: never;
    query?: never;
    url: '/api/adm/program/getProgram';
};

export type ProgramsControllerGetProgramResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type ProgramsControllerGetProgramResponse = ProgramsControllerGetProgramResponses[keyof ProgramsControllerGetProgramResponses];

export type ProgramsControllerInsertProgramData = {
    body: ProgramDto;
    path?: never;
    query?: never;
    url: '/api/adm/program/insertProgram';
};

export type ProgramsControllerInsertProgramResponses = {
    200: SuccessDto;
};

export type ProgramsControllerInsertProgramResponse = ProgramsControllerInsertProgramResponses[keyof ProgramsControllerInsertProgramResponses];

export type ProgramsControllerUpdateProgramData = {
    body: ProgramDto;
    path?: never;
    query?: never;
    url: '/api/adm/program/updateProgram';
};

export type ProgramsControllerUpdateProgramResponses = {
    200: SuccessDto;
};

export type ProgramsControllerUpdateProgramResponse = ProgramsControllerUpdateProgramResponses[keyof ProgramsControllerUpdateProgramResponses];

export type ProgramsControllerDeleteProgramsData = {
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/api/adm/program/deletePrograms';
};

export type ProgramsControllerDeleteProgramsResponses = {
    200: SuccessDto;
};

export type ProgramsControllerDeleteProgramsResponse = ProgramsControllerDeleteProgramsResponses[keyof ProgramsControllerDeleteProgramsResponses];

export type ProgramsControllerGetPermissionByProgramData = {
    body: SearchProgramDto;
    path?: never;
    query?: never;
    url: '/api/adm/program/getPermissionByProgram';
};

export type ProgramsControllerGetPermissionByProgramResponses = {
    200: Array<PermissionDto>;
};

export type ProgramsControllerGetPermissionByProgramResponse = ProgramsControllerGetPermissionByProgramResponses[keyof ProgramsControllerGetPermissionByProgramResponses];

export type ProgramsControllerSavePermissionsByProgramData = {
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/api/adm/program/savePermissionsByProgram';
};

export type ProgramsControllerSavePermissionsByProgramResponses = {
    200: SuccessDto;
};

export type ProgramsControllerSavePermissionsByProgramResponse = ProgramsControllerSavePermissionsByProgramResponses[keyof ProgramsControllerSavePermissionsByProgramResponses];

export type RolesControllerGetRoleListData = {
    body: SearchRoleDto;
    path?: never;
    query?: never;
    url: '/api/adm/role/getRoleList';
};

export type RolesControllerGetRoleListResponses = {
    200: RoleListDto;
};

export type RolesControllerGetRoleListResponse = RolesControllerGetRoleListResponses[keyof RolesControllerGetRoleListResponses];

export type RolesControllerGetRoleData = {
    body: SearchRoleDto;
    path?: never;
    query?: never;
    url: '/api/adm/role/getRole';
};

export type RolesControllerGetRoleResponses = {
    200: RoleDto;
};

export type RolesControllerGetRoleResponse = RolesControllerGetRoleResponses[keyof RolesControllerGetRoleResponses];

export type RolesControllerInsertRoleData = {
    body: RoleDto;
    path?: never;
    query?: never;
    url: '/api/adm/role/insertRole';
};

export type RolesControllerInsertRoleResponses = {
    200: SuccessDto;
};

export type RolesControllerInsertRoleResponse = RolesControllerInsertRoleResponses[keyof RolesControllerInsertRoleResponses];

export type RolesControllerUpdateRoleData = {
    body: RoleDto;
    path?: never;
    query?: never;
    url: '/api/adm/role/updateRole';
};

export type RolesControllerUpdateRoleResponses = {
    200: SuccessDto;
};

export type RolesControllerUpdateRoleResponse = RolesControllerUpdateRoleResponses[keyof RolesControllerUpdateRoleResponses];
