org.quartz.scheduler.instanceName=blueprint-html
org.quartz.scheduler.instanceId=AUTO
org.quartz.threadPool.threadCount=10
org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
org.quartz.jobStore.misfireThreshold=600000
org.quartz.jobStore.tablePrefix=qrtz_
org.quartz.jobStore.isClustered=false
org.quartz.jobStore.clusterCheckinInterval=15000
org.quartz.scheduler.classLoadHelper.class=org.quartz.simpl.ThreadContextClassLoadHelper
org.quartz.jobStore.dataSource=quartzDS
org.quartz.dataSource.quartzDS.provider=hikaricp
org.quartz.dataSource.quartzDS.driver=org.postgresql.Driver
org.quartz.dataSource.quartzDS.URL=jdbc:postgresql://10.0.0.85:5432/erp-dev?currentSchema=quartz
org.quartz.dataSource.quartzDS.user=postgres
org.quartz.dataSource.quartzDS.password=postgres
org.quartz.dataSource.quartzDS.maxConnections=5
org.quartz.dataSource.quartzDS.minimumIdle=1
org.quartz.dataSource.quartzDS.idleTimeout=300000
org.quartz.dataSource.quartzDS.maxLifetime=1800000
org.quartz.dataSource.quartzDS.connectionTimeout=30000
org.quartz.dataSource.quartzDS.leakDetectionThreshold=60000