/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PAvatar: typeof import('primevue/avatar')['default']
    PBadge: typeof import('primevue/badge')['default']
    PBreadcrumb: typeof import('primevue/breadcrumb')['default']
    PButton: typeof import('primevue/button')['default']
    PCard: typeof import('primevue/card')['default']
    PCheckbox: typeof import('primevue/checkbox')['default']
    PDivider: typeof import('primevue/divider')['default']
    PDrawer: typeof import('primevue/drawer')['default']
    PIconField: typeof import('primevue/iconfield')['default']
    PInputIcon: typeof import('primevue/inputicon')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMenu: typeof import('primevue/menu')['default']
    PPassword: typeof import('primevue/password')['default']
    PPopover: typeof import('primevue/popover')['default']
    PToast: typeof import('primevue/toast')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
