// This file is auto-generated by @hey-api/openapi-ts

export type ErrorResponseDto = {
    errorCode?: string;
    errorMessage?: string;
    systemMessage?: string;
};

export type PermissionDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    pgmId?: string;
    permId?: string;
    permCd?: string;
    permNm?: string;
};

export type ProgramDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    pgmId?: string;
    pgmCd?: string;
    pgmNm?: string;
    pgmTpCd?: string;
    prntPgmId?: string;
    pgmRmk?: string;
    dspOrder?: number;
    level?: number;
    treeKey?: string;
    treePath?: string;
    permList?: Array<PermissionDto>;
};

export type SuccessDto = {
    success?: boolean;
    rows?: number;
};

export type DynamicFilterDto = {
    field?: string;
    operator?: string;
    value?: unknown;
    valueTo?: unknown;
    valueType?: string;
};

export type PaginationDto = {
    pageSize?: number;
    current?: number;
};

export type SearchProgramDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    searchText?: string;
    filters?: Array<DynamicFilterDto>;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    pagination?: PaginationDto;
    pgmId?: string;
    pgmCd?: string;
    pgmNm?: string;
    pgmTpCd?: string;
};

export type SortDto = {
    sortField?: string;
    sortType?: string;
};

export type ProgramListDto = {
    programList?: Array<ProgramDto>;
    total?: number;
};

export type FavoriteDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    favId?: number;
    usrId?: string;
    pgmCd?: string;
};

export type SearchExportJobDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    searchText?: string;
    filters?: Array<DynamicFilterDto>;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    pagination?: PaginationDto;
    jbId?: string;
    jbIds?: Array<string>;
};

export type ExportJobDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    jbId?: string;
    jbSts?: string;
    jbProg?: number;
    jbRqstPara?: JsonNode;
    errMsg?: string;
    fileNm?: string;
    fileId?: string;
    totalRows?: number;
};

export type ExportJobListDto = {
    jobs?: Array<ExportJobDto>;
    total?: number;
};

export type JsonNode = unknown;

export type SearchExceptionLogDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    searchText?: string;
    filters?: Array<DynamicFilterDto>;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    pagination?: PaginationDto;
    dateFm?: string;
    dateTo?: string;
    endPoint?: string;
};

export type ExceptionLogDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    msgId?: string;
    errMsg?: string;
    endpoint?: string;
    rqstPara?: JsonNode;
    mdlNm?: string;
    stackTrace?: string;
};

export type ExceptionLogListDto = {
    messageList?: Array<ExceptionLogDto>;
    total?: number;
};

export type SendEmailRequestDto = {
    to?: string;
    cc?: string;
    bcc?: string;
    subject?: string;
    htmlContent?: string;
    attachments?: Array<Blob | File>;
};

export type EmailDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    emlId?: string;
    emlTo?: string;
    emlCc?: string;
    emlBcc?: string;
    emlSubjVal?: string;
    emlCntnVal?: string;
    emlSndStsCd?: string;
    emlAtchId?: string;
    emlSysMsg?: string;
    emlFalRsn?: string;
};

export type EmailAttachmentDetailDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    emlAtchId?: string;
    fileId?: string;
    fileNm?: string;
    fileTp?: string;
    fileSz?: number;
    dspOrdVal?: number;
};

export type EmailDetailDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    emlId?: string;
    emlTo?: string;
    emlCc?: string;
    emlBcc?: string;
    emlSubjVal?: string;
    emlCntnVal?: string;
    emlSndStsCd?: string;
    emlSysMsg?: string;
    emlAtchId?: string;
    attachments?: Array<EmailAttachmentDetailDto>;
};

export type SearchEmailDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    searchText?: string;
    filters?: Array<DynamicFilterDto>;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    pagination?: PaginationDto;
    fromDate?: string;
    toDate?: string;
    emlSndStsCd?: string;
    emlTo?: string;
    emlSubjVal?: string;
    emlSysMsg?: string;
    sysMsgPrefix?: string;
    statuses?: Array<string>;
    batchSize?: number;
    staleMinutes?: number;
    sysMsgs?: Array<string>;
};

export type EmailListDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    emlId?: string;
    emlTo?: string;
    emlCc?: string;
    emlBcc?: string;
    emlSubjVal?: string;
    emlSndStsCd?: string;
    emlSysMsg?: string;
    emlAtchId?: string;
};

export type EmailListResultDto = {
    emails?: Array<EmailListDto>;
    total?: number;
};

export type MessageDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    msgId?: string;
    dfltMsgVal?: string;
    mdlNm?: string;
    msgTpVal?: string;
    translations?: Array<MessageTranslationDto>;
};

export type MessageTranslationDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    msgId?: string;
    langVal?: string;
    transMsgVal?: string;
};

export type SearchMessageDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    searchText?: string;
    filters?: Array<DynamicFilterDto>;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    pagination?: PaginationDto;
    msgId?: string;
    dfltMsgVal?: string;
    mdlNm?: string;
    msgTpVal?: string;
    langVal?: string;
};

export type MessageListDto = {
    messageList?: Array<MessageDto>;
    total?: number;
};

export type BatchJobConfigDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    batJbId?: string;
    batJbNm?: string;
    batJbClss?: string;
    batJbStsCd?: string;
    batJbDesc?: string;
    cronXprVal?: string;
    cronDesc?: string;
    jobParams?: {
        [key: string]: unknown;
    };
    batJbLstRunDt?: string;
    batJbNxtRunDt?: string;
};

export type SearchBatchJobConfigDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    searchText?: string;
    filters?: Array<DynamicFilterDto>;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    pagination?: PaginationDto;
    batJbId?: string;
    batJbNm?: string;
};

export type SearchBatchJobExecutionHistoryDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    searchText?: string;
    filters?: Array<DynamicFilterDto>;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    pagination?: PaginationDto;
    batJbId?: string;
};

export type BatchJobExecutionHistoryDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    batExecId?: string;
    batJbId?: string;
    batJbStsCd?: string;
    batJbStDt?: string;
    batJbEndDt?: string;
    batJbPara?: JsonNode;
    batJbMsg?: string;
    batJbNxtRunDt?: string;
};

export type BatchJobExecutionHistoryListDto = {
    executionHistory?: Array<BatchJobExecutionHistoryDto>;
    total?: number;
};

export type SearchReportDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    searchText?: string;
    filters?: Array<DynamicFilterDto>;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    pagination?: PaginationDto;
    rptId?: string;
    rptCd?: string;
    rptNm?: string;
    pgmId?: string;
    pgmCd?: string;
    textSearch?: string;
};

export type ReportDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    rptId?: string;
    rptCd?: string;
    rptNm?: string;
    rptFileId?: string;
    rptFileName?: string;
    pgmId?: string;
    pgmNm?: string;
    rptUrl?: string;
};

export type ReportListDto = {
    reportList?: Array<ReportDto>;
    total?: number;
};

export type FileDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    fileId?: string;
    fileNm?: string;
    filePath?: string;
    fileTp?: string;
    fileSz?: number;
    file?: Blob | File;
};

export type SubCodeDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    mstCd?: string;
    subCd?: string;
    subNm?: string;
    subDesc?: string;
    subOrdNo?: number;
    attrCtnt1?: string;
    attrCtnt2?: string;
    attrCtnt3?: string;
    attrCtnt4?: string;
    attrCtnt5?: string;
    attrCtnt6?: string;
    attrCtnt7?: string;
    attrCtnt8?: string;
    attrCtnt9?: string;
    attrCtnt10?: string;
    attrCtnt11?: string;
    attrCtnt12?: string;
    attrCtnt13?: string;
    attrCtnt14?: string;
    attrCtnt15?: string;
    attrCtnt16?: string;
    attrCtnt17?: string;
    attrCtnt18?: string;
    attrCtnt19?: string;
    attrCtnt20?: string;
    dfltFlg?: string;
};

export type MasterCodeDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    mstCd?: string;
    mstNm?: string;
    mstMdlNm?: string;
    mstDesc?: string;
    subTblCfg?: JsonNode;
    subCodes?: Array<SubCodeDto>;
};

export type SearchMasterCodeDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    searchText?: string;
    filters?: Array<DynamicFilterDto>;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    pagination?: PaginationDto;
    mstCd?: string;
    mstNm?: string;
    mstMdlNm?: string;
};

export type MasterCodeListDto = {
    masterCodes?: Array<MasterCodeDto>;
    total?: number;
};

export type GetCommonCodeRequestDto = {
    coId: string;
    cdList: Array<string>;
};

export type SubCodeResponseDto = {
    coId?: string;
    mstCd?: string;
    subCd?: string;
    subNm?: string;
    subDesc?: string;
    subOrdNo?: number;
    attrCtnt1?: string;
    attrCtnt2?: string;
    attrCtnt3?: string;
    attrCtnt4?: string;
    attrCtnt5?: string;
    attrCtnt6?: string;
    attrCtnt7?: string;
    attrCtnt8?: string;
    attrCtnt9?: string;
    attrCtnt10?: string;
    attrCtnt11?: string;
    attrCtnt12?: string;
    attrCtnt13?: string;
    attrCtnt14?: string;
    attrCtnt15?: string;
    attrCtnt16?: string;
    attrCtnt17?: string;
    attrCtnt18?: string;
    attrCtnt19?: string;
    attrCtnt20?: string;
    dfltFlg?: string;
};

export type UserInfoDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    usrId?: string;
    usrPwd?: string;
    usrNm?: string;
    usrEml?: string;
    roleId?: string;
    roleNm?: string;
    langVal?: string;
    sysModVal?: string;
    dtFmtVal?: string;
    sysColrVal?: string;
    usrPhn?: string;
    usrAddr?: string;
    usrDesc?: string;
    usrFileId?: string;
    usrFileDto?: FileDto;
};

export type SearchUserDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    searchText?: string;
    filters?: Array<DynamicFilterDto>;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    pagination?: PaginationDto;
    usrId?: string;
    usrNm?: string;
};

export type UserInfoListDto = {
    userInfo?: Array<UserInfoDto>;
    total?: number;
};

/**
 * Request payload for changing user information and/or password
 */
export type ChangeUserInfoDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    usrId?: string;
    usrPwd?: string;
    usrNm?: string;
    usrEml?: string;
    roleId?: string;
    roleNm?: string;
    langVal?: string;
    sysModVal?: string;
    dtFmtVal?: string;
    sysColrVal?: string;
    usrPhn?: string;
    usrAddr?: string;
    usrDesc?: string;
    usrFileId?: string;
    usrFileDto?: FileDto;
    /**
     * Current password (required only when changing password)
     */
    oldPassword?: string;
    /**
     * New password (required only when changing password, minimum 8 characters, strong password required)
     */
    newPassword?: string;
    /**
     * Confirmation of the new password (required only when changing password, must match newPassword)
     */
    confirmNewPassword?: string;
};

export type RoleAuthDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    roleId?: string;
    pgmId?: string;
    permId?: string;
    pgmCd?: string;
    pgmTpCd?: string;
    permCd?: string;
    activeYn?: string;
};

export type RoleDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    roleId?: string;
    roleCd?: string;
    roleNm?: string;
    roleDesc?: string;
    roleAuthList?: Array<RoleAuthDto>;
};

export type SearchRoleDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    searchText?: string;
    filters?: Array<DynamicFilterDto>;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    pagination?: PaginationDto;
    roleId?: string;
    roleCd?: string;
    roleNm?: string;
    pgmId?: string;
    permId?: string;
};

export type RoleListDto = {
    roleList?: Array<RoleDto>;
    total?: number;
};

export type CompanyInfoDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    coNm?: string;
    coTpCd?: string;
    coFrgnNm?: string;
    taxCd?: string;
    taxOfc?: string;
    coLoclNm?: string;
    coAddrVal1?: string;
    coAddrVal2?: string;
    coAddrVal3?: string;
    emlAddr?: string;
    faxNo?: string;
    phnNo?: string;
    slRep?: string;
    webAddr?: string;
    coDesc?: string;
    coAnvDt?: string;
    coSz?: string;
    coNtn?: string;
    empeSz?: string;
    currCd?: string;
    coIndusZn?: string;
    coProd?: string;
    tmZn?: string;
    bankTpCd?: string;
    bankAcctNo?: string;
    bankNm?: string;
    chtrCapiVal?: number;
    estbDt?: string;
    lgoFileId?: string;
    logoFile?: Blob | File;
    logoFileDto?: FileDto;
};

export type SearchCompanyDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    searchText?: string;
    filters?: Array<DynamicFilterDto>;
    sort?: SortDto;
    sorts?: Array<SortDto>;
    pagination?: PaginationDto;
    taxCd?: string;
    coTpCd?: string;
    coNtn?: string;
};

export type CompanyInfoListDto = {
    companyInfo?: Array<CompanyInfoDto>;
    total?: number;
};

export type RefreshTokenRequestDto = {
    refreshToken?: string;
};

export type RefreshTokenResponseDto = {
    accessToken?: string;
    accessExpireIn?: number;
    refreshToken?: string;
    refreshExpireIn?: number;
};

export type LoginRequestDto = {
    username?: string;
    password?: string;
};

export type LoginResponseDto = {
    accessToken?: string;
    accessExpireIn?: number;
    refreshToken?: string;
    refreshExpireIn?: number;
};

export type RoleAuthInfoDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    roleId?: string;
    pgmId?: string;
    permId?: string;
    pgmCd?: string;
    pgmTpCd?: string;
    permCd?: string;
    activeYn?: string;
};

export type RoleInfoDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    roleId?: string;
    roleCd?: string;
    roleNm?: string;
    roleDesc?: string;
    roleAuthList?: Array<RoleAuthInfoDto>;
};

export type UpdateProgramData = {
    body: ProgramDto;
    path?: never;
    query?: never;
    url: '/api/sys/program/updateProgram';
};

export type UpdateProgramErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UpdateProgramError = UpdateProgramErrors[keyof UpdateProgramErrors];

export type UpdateProgramResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UpdateProgramResponse = UpdateProgramResponses[keyof UpdateProgramResponses];

export type SavePermissionByProgramData = {
    body: Array<PermissionDto>;
    path?: never;
    query?: never;
    url: '/api/sys/program/savePermissionsByProgram';
};

export type SavePermissionByProgramErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type SavePermissionByProgramError = SavePermissionByProgramErrors[keyof SavePermissionByProgramErrors];

export type SavePermissionByProgramResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type SavePermissionByProgramResponse = SavePermissionByProgramResponses[keyof SavePermissionByProgramResponses];

export type InsertProgramData = {
    body: ProgramDto;
    path?: never;
    query?: never;
    url: '/api/sys/program/insertProgram';
};

export type InsertProgramErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type InsertProgramError = InsertProgramErrors[keyof InsertProgramErrors];

export type InsertProgramResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type InsertProgramResponse = InsertProgramResponses[keyof InsertProgramResponses];

export type GetProgramData = {
    body: SearchProgramDto;
    path?: never;
    query?: never;
    url: '/api/sys/program/getProgram';
};

export type GetProgramErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetProgramError = GetProgramErrors[keyof GetProgramErrors];

export type GetProgramResponses = {
    /**
     * OK
     */
    200: ProgramDto;
};

export type GetProgramResponse = GetProgramResponses[keyof GetProgramResponses];

export type GetProgramListData = {
    body: SearchProgramDto;
    path?: never;
    query?: never;
    url: '/api/sys/program/getProgramList';
};

export type GetProgramListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetProgramListError = GetProgramListErrors[keyof GetProgramListErrors];

export type GetProgramListResponses = {
    /**
     * OK
     */
    200: ProgramListDto;
};

export type GetProgramListResponse = GetProgramListResponses[keyof GetProgramListResponses];

export type GetPermissionByProgramData = {
    body: ProgramDto;
    path?: never;
    query?: never;
    url: '/api/sys/program/getPermissionByProgram';
};

export type GetPermissionByProgramErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetPermissionByProgramError = GetPermissionByProgramErrors[keyof GetPermissionByProgramErrors];

export type GetPermissionByProgramResponses = {
    /**
     * OK
     */
    200: Array<PermissionDto>;
};

export type GetPermissionByProgramResponse = GetPermissionByProgramResponses[keyof GetPermissionByProgramResponses];

export type DeleteProgramData = {
    body: Array<ProgramDto>;
    path?: never;
    query?: never;
    url: '/api/sys/program/deletePrograms';
};

export type DeleteProgramErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type DeleteProgramError = DeleteProgramErrors[keyof DeleteProgramErrors];

export type DeleteProgramResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type DeleteProgramResponse = DeleteProgramResponses[keyof DeleteProgramResponses];

export type GetUserFavoritesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sys/favorites';
};

export type GetUserFavoritesErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetUserFavoritesError = GetUserFavoritesErrors[keyof GetUserFavoritesErrors];

export type GetUserFavoritesResponses = {
    /**
     * OK
     */
    200: Array<FavoriteDto>;
};

export type GetUserFavoritesResponse = GetUserFavoritesResponses[keyof GetUserFavoritesResponses];

export type AddFavoriteData = {
    body: FavoriteDto;
    path?: never;
    query?: never;
    url: '/api/sys/favorites';
};

export type AddFavoriteErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type AddFavoriteError = AddFavoriteErrors[keyof AddFavoriteErrors];

export type AddFavoriteResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type AddFavoriteResponse = AddFavoriteResponses[keyof AddFavoriteResponses];

export type GetExportJobListData = {
    body: SearchExportJobDto;
    path?: never;
    query?: never;
    url: '/api/sys/exportJob/getExportJobList';
};

export type GetExportJobListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetExportJobListError = GetExportJobListErrors[keyof GetExportJobListErrors];

export type GetExportJobListResponses = {
    /**
     * OK
     */
    200: ExportJobListDto;
};

export type GetExportJobListResponse = GetExportJobListResponses[keyof GetExportJobListResponses];

export type GetHistoryListData = {
    body: SearchExceptionLogDto;
    path?: never;
    query?: never;
    url: '/api/sys/errorLog/getHistoryList';
};

export type GetHistoryListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetHistoryListError = GetHistoryListErrors[keyof GetHistoryListErrors];

export type GetHistoryListResponses = {
    /**
     * OK
     */
    200: ExceptionLogListDto;
};

export type GetHistoryListResponse = GetHistoryListResponses[keyof GetHistoryListResponses];

export type SendEmailData = {
    body?: SendEmailRequestDto;
    path?: never;
    query?: never;
    url: '/api/sys/email/sendEmail';
};

export type SendEmailErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type SendEmailError = SendEmailErrors[keyof SendEmailErrors];

export type SendEmailResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type SendEmailResponse = SendEmailResponses[keyof SendEmailResponses];

export type ResendEmailsData = {
    body: Array<EmailDto>;
    path?: never;
    query?: never;
    url: '/api/sys/email/resendEmails';
};

export type ResendEmailsErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type ResendEmailsError = ResendEmailsErrors[keyof ResendEmailsErrors];

export type ResendEmailsResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type ResendEmailsResponse = ResendEmailsResponses[keyof ResendEmailsResponses];

export type ResendEmailData = {
    body: EmailDto;
    path?: never;
    query?: never;
    url: '/api/sys/email/resendEmail';
};

export type ResendEmailErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type ResendEmailError = ResendEmailErrors[keyof ResendEmailErrors];

export type ResendEmailResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type ResendEmailResponse = ResendEmailResponses[keyof ResendEmailResponses];

export type GetEmailData = {
    body: EmailDto;
    path?: never;
    query?: never;
    url: '/api/sys/email/getEmail';
};

export type GetEmailErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetEmailError = GetEmailErrors[keyof GetEmailErrors];

export type GetEmailResponses = {
    /**
     * OK
     */
    200: EmailDetailDto;
};

export type GetEmailResponse = GetEmailResponses[keyof GetEmailResponses];

export type GetEmailListData = {
    body: SearchEmailDto;
    path?: never;
    query?: never;
    url: '/api/sys/email/getEmailList';
};

export type GetEmailListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetEmailListError = GetEmailListErrors[keyof GetEmailListErrors];

export type GetEmailListResponses = {
    /**
     * OK
     */
    200: EmailListResultDto;
};

export type GetEmailListResponse = GetEmailListResponses[keyof GetEmailListResponses];

export type DeleteEmailsData = {
    body: Array<EmailDto>;
    path?: never;
    query?: never;
    url: '/api/sys/email/deleteEmails';
};

export type DeleteEmailsErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type DeleteEmailsError = DeleteEmailsErrors[keyof DeleteEmailsErrors];

export type DeleteEmailsResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type DeleteEmailsResponse = DeleteEmailsResponses[keyof DeleteEmailsResponses];

export type UpdateMessageData = {
    body: MessageDto;
    path?: never;
    query?: never;
    url: '/api/sys/comMsg/updateMessage';
};

export type UpdateMessageErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UpdateMessageError = UpdateMessageErrors[keyof UpdateMessageErrors];

export type UpdateMessageResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UpdateMessageResponse = UpdateMessageResponses[keyof UpdateMessageResponses];

export type InsertMessageData = {
    body: MessageDto;
    path?: never;
    query?: never;
    url: '/api/sys/comMsg/insertMessage';
};

export type InsertMessageErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type InsertMessageError = InsertMessageErrors[keyof InsertMessageErrors];

export type InsertMessageResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type InsertMessageResponse = InsertMessageResponses[keyof InsertMessageResponses];

export type GetMessageData = {
    body: SearchMessageDto;
    path?: never;
    query?: never;
    url: '/api/sys/comMsg/getMessage';
};

export type GetMessageErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetMessageError = GetMessageErrors[keyof GetMessageErrors];

export type GetMessageResponses = {
    /**
     * OK
     */
    200: MessageDto;
};

export type GetMessageResponse = GetMessageResponses[keyof GetMessageResponses];

export type GetMessageListData = {
    body: SearchMessageDto;
    path?: never;
    query?: never;
    url: '/api/sys/comMsg/getMessageList';
};

export type GetMessageListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetMessageListError = GetMessageListErrors[keyof GetMessageListErrors];

export type GetMessageListResponses = {
    /**
     * OK
     */
    200: MessageListDto;
};

export type GetMessageListResponse = GetMessageListResponses[keyof GetMessageListResponses];

export type DeleteMessageData = {
    body: Array<MessageDto>;
    path?: never;
    query?: never;
    url: '/api/sys/comMsg/deleteMessage';
};

export type DeleteMessageErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type DeleteMessageError = DeleteMessageErrors[keyof DeleteMessageErrors];

export type DeleteMessageResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type DeleteMessageResponse = DeleteMessageResponses[keyof DeleteMessageResponses];

export type UpdateData = {
    body: BatchJobConfigDto;
    path?: never;
    query?: never;
    url: '/api/sys/batch/update';
};

export type UpdateErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UpdateError = UpdateErrors[keyof UpdateErrors];

export type UpdateResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type RunJobData = {
    body: BatchJobConfigDto;
    path?: never;
    query?: never;
    url: '/api/sys/batch/run';
};

export type RunJobErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type RunJobError = RunJobErrors[keyof RunJobErrors];

export type RunJobResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type RunJobResponse = RunJobResponses[keyof RunJobResponses];

export type ResumeJobData = {
    body: BatchJobConfigDto;
    path?: never;
    query?: never;
    url: '/api/sys/batch/resume';
};

export type ResumeJobErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type ResumeJobError = ResumeJobErrors[keyof ResumeJobErrors];

export type ResumeJobResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type ResumeJobResponse = ResumeJobResponses[keyof ResumeJobResponses];

export type RegisterData = {
    body: BatchJobConfigDto;
    path?: never;
    query?: never;
    url: '/api/sys/batch/register';
};

export type RegisterErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type PauseJobData = {
    body: BatchJobConfigDto;
    path?: never;
    query?: never;
    url: '/api/sys/batch/pause';
};

export type PauseJobErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type PauseJobError = PauseJobErrors[keyof PauseJobErrors];

export type PauseJobResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type PauseJobResponse = PauseJobResponses[keyof PauseJobResponses];

export type GetBatchJobData = {
    body: SearchBatchJobConfigDto;
    path?: never;
    query?: never;
    url: '/api/sys/batch/getBatchJob';
};

export type GetBatchJobErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetBatchJobError = GetBatchJobErrors[keyof GetBatchJobErrors];

export type GetBatchJobResponses = {
    /**
     * OK
     */
    200: BatchJobConfigDto;
};

export type GetBatchJobResponse = GetBatchJobResponses[keyof GetBatchJobResponses];

export type GetBatchJobListData = {
    body: SearchBatchJobConfigDto;
    path?: never;
    query?: never;
    url: '/api/sys/batch/getBatchJobList';
};

export type GetBatchJobListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetBatchJobListError = GetBatchJobListErrors[keyof GetBatchJobListErrors];

export type GetBatchJobListResponses = {
    /**
     * OK
     */
    200: Array<BatchJobConfigDto>;
};

export type GetBatchJobListResponse = GetBatchJobListResponses[keyof GetBatchJobListResponses];

export type GetBatchJobHistoryListData = {
    body: SearchBatchJobExecutionHistoryDto;
    path?: never;
    query?: never;
    url: '/api/sys/batch/getBatchJobHistoryList';
};

export type GetBatchJobHistoryListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetBatchJobHistoryListError = GetBatchJobHistoryListErrors[keyof GetBatchJobHistoryListErrors];

export type GetBatchJobHistoryListResponses = {
    /**
     * OK
     */
    200: BatchJobExecutionHistoryListDto;
};

export type GetBatchJobHistoryListResponse = GetBatchJobHistoryListResponses[keyof GetBatchJobHistoryListResponses];

export type UpdateReportData = {
    body?: {
        report: string;
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/com/reports/update';
};

export type UpdateReportErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UpdateReportError = UpdateReportErrors[keyof UpdateReportErrors];

export type UpdateReportResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UpdateReportResponse = UpdateReportResponses[keyof UpdateReportResponses];

export type GetReportListData = {
    body: SearchReportDto;
    path?: never;
    query?: never;
    url: '/api/com/reports/list';
};

export type GetReportListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetReportListError = GetReportListErrors[keyof GetReportListErrors];

export type GetReportListResponses = {
    /**
     * OK
     */
    200: ReportListDto;
};

export type GetReportListResponse = GetReportListResponses[keyof GetReportListResponses];

export type InsertReportData = {
    body?: {
        report: string;
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/com/reports/insert';
};

export type InsertReportErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type InsertReportError = InsertReportErrors[keyof InsertReportErrors];

export type InsertReportResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type InsertReportResponse = InsertReportResponses[keyof InsertReportResponses];

export type DownloadTestExcelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/com/reports/downloadTestExcel';
};

export type DownloadTestExcelErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type DownloadTestExcelError = DownloadTestExcelErrors[keyof DownloadTestExcelErrors];

export type DownloadTestExcelResponses = {
    /**
     * OK
     */
    200: string;
};

export type DownloadTestExcelResponse = DownloadTestExcelResponses[keyof DownloadTestExcelResponses];

export type DeleteReportData = {
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/api/com/reports/delete';
};

export type DeleteReportErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type DeleteReportError = DeleteReportErrors[keyof DeleteReportErrors];

export type DeleteReportResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type DeleteReportResponse = DeleteReportResponses[keyof DeleteReportResponses];

export type UploadData = {
    body?: never;
    path?: never;
    query: {
        file: FileDto;
        subPath?: string;
    };
    url: '/api/com/file/upload';
};

export type UploadErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UploadError = UploadErrors[keyof UploadErrors];

export type UploadResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UploadResponse = UploadResponses[keyof UploadResponses];

export type SaveSubCodeData = {
    body: Array<SubCodeDto>;
    path?: never;
    query?: never;
    url: '/api/com/code/saveSubCode';
};

export type SaveSubCodeErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type SaveSubCodeError = SaveSubCodeErrors[keyof SaveSubCodeErrors];

export type SaveSubCodeResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type SaveSubCodeResponse = SaveSubCodeResponses[keyof SaveSubCodeResponses];

export type SaveMasterCodeData = {
    body: Array<MasterCodeDto>;
    path?: never;
    query?: never;
    url: '/api/com/code/saveMasterCode';
};

export type SaveMasterCodeErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type SaveMasterCodeError = SaveMasterCodeErrors[keyof SaveMasterCodeErrors];

export type SaveMasterCodeResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type SaveMasterCodeResponse = SaveMasterCodeResponses[keyof SaveMasterCodeResponses];

export type GetMasterCodeData = {
    body: SearchMasterCodeDto;
    path?: never;
    query?: never;
    url: '/api/com/code/getMasterCode';
};

export type GetMasterCodeErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetMasterCodeError = GetMasterCodeErrors[keyof GetMasterCodeErrors];

export type GetMasterCodeResponses = {
    /**
     * OK
     */
    200: MasterCodeDto;
};

export type GetMasterCodeResponse = GetMasterCodeResponses[keyof GetMasterCodeResponses];

export type GetListMasterCodeData = {
    body: SearchMasterCodeDto;
    path?: never;
    query?: never;
    url: '/api/com/code/getListMasterCode';
};

export type GetListMasterCodeErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetListMasterCodeError = GetListMasterCodeErrors[keyof GetListMasterCodeErrors];

export type GetListMasterCodeResponses = {
    /**
     * OK
     */
    200: MasterCodeListDto;
};

export type GetListMasterCodeResponse = GetListMasterCodeResponses[keyof GetListMasterCodeResponses];

export type GetCommonCodeData = {
    body: GetCommonCodeRequestDto;
    path?: never;
    query?: never;
    url: '/api/com/code/getCommonCode';
};

export type GetCommonCodeErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetCommonCodeError = GetCommonCodeErrors[keyof GetCommonCodeErrors];

export type GetCommonCodeResponses = {
    /**
     * OK
     */
    200: Array<Array<SubCodeResponseDto>>;
};

export type GetCommonCodeResponse = GetCommonCodeResponses[keyof GetCommonCodeResponses];

export type UpdateUserData = {
    body: UserInfoDto;
    path?: never;
    query?: never;
    url: '/api/adm/user/updateUser';
};

export type UpdateUserErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type SaveUserSettingData = {
    body: UserInfoDto;
    path?: never;
    query?: never;
    url: '/api/adm/user/saveUserSetting';
};

export type SaveUserSettingErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type SaveUserSettingError = SaveUserSettingErrors[keyof SaveUserSettingErrors];

export type SaveUserSettingResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type SaveUserSettingResponse = SaveUserSettingResponses[keyof SaveUserSettingResponses];

export type ResetUserPasswordData = {
    body: Array<UserInfoDto>;
    path?: never;
    query?: never;
    url: '/api/adm/user/resetUserPassword';
};

export type ResetUserPasswordErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type ResetUserPasswordError = ResetUserPasswordErrors[keyof ResetUserPasswordErrors];

export type ResetUserPasswordResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type ResetUserPasswordResponse = ResetUserPasswordResponses[keyof ResetUserPasswordResponses];

export type GetUserInfoData = {
    body: SearchUserDto;
    path?: never;
    query?: never;
    url: '/api/adm/user/getUserInfo';
};

export type GetUserInfoErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetUserInfoError = GetUserInfoErrors[keyof GetUserInfoErrors];

export type GetUserInfoResponses = {
    /**
     * OK
     */
    200: UserInfoDto;
};

export type GetUserInfoResponse = GetUserInfoResponses[keyof GetUserInfoResponses];

export type GetListUserInfoData = {
    body: SearchUserDto;
    path?: never;
    query?: never;
    url: '/api/adm/user/getListUserInfo';
};

export type GetListUserInfoErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetListUserInfoError = GetListUserInfoErrors[keyof GetListUserInfoErrors];

export type GetListUserInfoResponses = {
    /**
     * OK
     */
    200: UserInfoListDto;
};

export type GetListUserInfoResponse = GetListUserInfoResponses[keyof GetListUserInfoResponses];

export type ExportExcelData = {
    body: SearchUserDto;
    path?: never;
    query?: never;
    url: '/api/adm/user/exportExcel';
};

export type ExportExcelErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type ExportExcelError = ExportExcelErrors[keyof ExportExcelErrors];

export type ExportExcelResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type ExportExcelResponse = ExportExcelResponses[keyof ExportExcelResponses];

export type CreateUserData = {
    body: UserInfoDto;
    path?: never;
    query?: never;
    url: '/api/adm/user/createUser';
};

export type CreateUserErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type ChangeUserInfoData = {
    body?: never;
    path?: never;
    query: {
        request: ChangeUserInfoDto;
    };
    url: '/api/adm/user/changeUserInfo';
};

export type ChangeUserInfoErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type ChangeUserInfoError = ChangeUserInfoErrors[keyof ChangeUserInfoErrors];

export type ChangeUserInfoResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type ChangeUserInfoResponse = ChangeUserInfoResponses[keyof ChangeUserInfoResponses];

export type UpdateRoleData = {
    body: RoleDto;
    path?: never;
    query?: never;
    url: '/api/adm/role/updateRole';
};

export type UpdateRoleErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UpdateRoleError = UpdateRoleErrors[keyof UpdateRoleErrors];

export type UpdateRoleResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UpdateRoleResponse = UpdateRoleResponses[keyof UpdateRoleResponses];

export type InsertRoleData = {
    body: RoleDto;
    path?: never;
    query?: never;
    url: '/api/adm/role/insertRole';
};

export type InsertRoleErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type InsertRoleError = InsertRoleErrors[keyof InsertRoleErrors];

export type InsertRoleResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type InsertRoleResponse = InsertRoleResponses[keyof InsertRoleResponses];

export type GetRoleData = {
    body: SearchRoleDto;
    path?: never;
    query?: never;
    url: '/api/adm/role/getRole';
};

export type GetRoleErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetRoleError = GetRoleErrors[keyof GetRoleErrors];

export type GetRoleResponses = {
    /**
     * OK
     */
    200: RoleDto;
};

export type GetRoleResponse = GetRoleResponses[keyof GetRoleResponses];

export type GetRoleListData = {
    body: SearchRoleDto;
    path?: never;
    query?: never;
    url: '/api/adm/role/getRoleList';
};

export type GetRoleListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetRoleListError = GetRoleListErrors[keyof GetRoleListErrors];

export type GetRoleListResponses = {
    /**
     * OK
     */
    200: RoleListDto;
};

export type GetRoleListResponse = GetRoleListResponses[keyof GetRoleListResponses];

export type UpdateCompanyData = {
    body?: never;
    path?: never;
    query: {
        request: CompanyInfoDto;
    };
    url: '/api/adm/company/updateCompany';
};

export type UpdateCompanyErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UpdateCompanyError = UpdateCompanyErrors[keyof UpdateCompanyErrors];

export type UpdateCompanyResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UpdateCompanyResponse = UpdateCompanyResponses[keyof UpdateCompanyResponses];

export type GetListCompanyInfoData = {
    body: SearchCompanyDto;
    path?: never;
    query?: never;
    url: '/api/adm/company/getListCompanyInfo';
};

export type GetListCompanyInfoErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetListCompanyInfoError = GetListCompanyInfoErrors[keyof GetListCompanyInfoErrors];

export type GetListCompanyInfoResponses = {
    /**
     * OK
     */
    200: CompanyInfoListDto;
};

export type GetListCompanyInfoResponse = GetListCompanyInfoResponses[keyof GetListCompanyInfoResponses];

export type GetCompanyInfoData = {
    body: SearchCompanyDto;
    path?: never;
    query?: never;
    url: '/api/adm/company/getCompanyInfo';
};

export type GetCompanyInfoErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetCompanyInfoError = GetCompanyInfoErrors[keyof GetCompanyInfoErrors];

export type GetCompanyInfoResponses = {
    /**
     * OK
     */
    200: CompanyInfoDto;
};

export type GetCompanyInfoResponse = GetCompanyInfoResponses[keyof GetCompanyInfoResponses];

export type CreateCompanyData = {
    body?: never;
    path?: never;
    query: {
        request: CompanyInfoDto;
    };
    url: '/api/adm/company/createCompany';
};

export type CreateCompanyErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type CreateCompanyError = CreateCompanyErrors[keyof CreateCompanyErrors];

export type CreateCompanyResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type CreateCompanyResponse = CreateCompanyResponses[keyof CreateCompanyResponses];

export type RefreshData = {
    body: RefreshTokenRequestDto;
    path?: never;
    query?: never;
    url: '/api/adm/auth/refresh-token';
};

export type RefreshErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * OK
     */
    200: RefreshTokenResponseDto;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/adm/auth/logout';
};

export type LogoutErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LoginData = {
    body: LoginRequestDto;
    path?: never;
    query?: never;
    url: '/api/adm/auth/login';
};

export type LoginErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * OK
     */
    200: LoginResponseDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type ConfirmExportData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/api/sys/exportJob/confirm/{jobId}';
};

export type ConfirmExportErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type ConfirmExportError = ConfirmExportErrors[keyof ConfirmExportErrors];

export type ConfirmExportResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type ConfirmExportResponse = ConfirmExportResponses[keyof ConfirmExportResponses];

export type CancelExportData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/api/sys/exportJob/cancel/{jobId}';
};

export type CancelExportErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type CancelExportError = CancelExportErrors[keyof CancelExportErrors];

export type CancelExportResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type CancelExportResponse = CancelExportResponses[keyof CancelExportResponses];

export type GetI18nMessagesForLanguageData = {
    body?: never;
    path: {
        lng: string;
    };
    query?: never;
    url: '/api/sys/comMsg/getI18nMessages/{lng}';
};

export type GetI18nMessagesForLanguageErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetI18nMessagesForLanguageError = GetI18nMessagesForLanguageErrors[keyof GetI18nMessagesForLanguageErrors];

export type GetI18nMessagesForLanguageResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetI18nMessagesForLanguageResponse = GetI18nMessagesForLanguageResponses[keyof GetI18nMessagesForLanguageResponses];

export type GetReportData = {
    body?: never;
    path: {
        rptCd: string;
    };
    query?: never;
    url: '/api/com/reports/{rptCd}';
};

export type GetReportErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetReportError = GetReportErrors[keyof GetReportErrors];

export type GetReportResponses = {
    /**
     * OK
     */
    200: ReportDto;
};

export type GetReportResponse = GetReportResponses[keyof GetReportResponses];

export type DownloadFileData = {
    body?: never;
    headers?: {
        Range?: string;
    };
    path: {
        fileId: string;
    };
    query?: {
        coId?: string;
    };
    url: '/api/com/file/download/{fileId}';
};

export type DownloadFileErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type DownloadFileError = DownloadFileErrors[keyof DownloadFileErrors];

export type DownloadFileResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadFileResponse = DownloadFileResponses[keyof DownloadFileResponses];

export type InvalidateSubCodeCacheData = {
    body?: never;
    path: {
        coId: string;
    };
    query?: never;
    url: '/api/com/code/invalidateSubCodeCache/{coId}';
};

export type InvalidateSubCodeCacheErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type InvalidateSubCodeCacheError = InvalidateSubCodeCacheErrors[keyof InvalidateSubCodeCacheErrors];

export type InvalidateSubCodeCacheResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type InvalidateSubCodeCacheResponse = InvalidateSubCodeCacheResponses[keyof InvalidateSubCodeCacheResponses];

export type GetUserRoleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/adm/auth/getUserRole';
};

export type GetUserRoleErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetUserRoleError = GetUserRoleErrors[keyof GetUserRoleErrors];

export type GetUserRoleResponses = {
    /**
     * OK
     */
    200: RoleInfoDto;
};

export type GetUserRoleResponse = GetUserRoleResponses[keyof GetUserRoleResponses];

export type RemoveFavoriteData = {
    body?: never;
    path: {
        pgmCd: string;
    };
    query?: never;
    url: '/api/sys/favorites/{pgmCd}';
};

export type RemoveFavoriteErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type RemoveFavoriteError = RemoveFavoriteErrors[keyof RemoveFavoriteErrors];

export type RemoveFavoriteResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type RemoveFavoriteResponse = RemoveFavoriteResponses[keyof RemoveFavoriteResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};